// eslint-disable-next-line no-shadow
enum activityTypes {
  FOLLOW_REQUEST = 'SUBSCRIBE_REQUEST',
  FOLLOW_SUCCESS = 'SUBSCRIBE_SUCCESS',
  FOLLOW_FAILTURE = 'SUBSCRIBE_FAILTURE',
  UN_FOLLOW_REQUEST = 'UN_SUBSCRIBE_REQUEST',
  UN_FOLLOW_SUCCESS = 'UN_SUBSCRIBE_SUCCESS',
  UN_FOLLOW_FAILTURE = 'UN_SUBSCRIBE_FAILTURE',
}

export {activityTypes};
