// eslint-disable-next-line no-shadow
enum chatsTypes {
  CHATS_REQUEST = 'CHATS_REQUEST',
  CHATS_REQUEST_SUCCESS = 'CHATS_REQUEST_SUCCESS',
  CHATS_REQUEST_FAILTURE = 'CHATS_REQUEST_FAILTURE',
}
// eslint-disable-next-line no-shadow
enum chatByIdTypes {
  CHAT_BY_ID_REQUEST = 'CHAT_BY_ID_REQUEST',
  CHAT_BY_ID_REQUEST_SUCCESS = 'CHAT_BY_ID_REQUEST_SUCCESS',
  CHAT_BY_ID_REQUEST_FAILTURE = 'CHAT_BY_ID_REQUEST_FAILTURE',
}
// eslint-disable-next-line no-shadow
enum messagesTypes {
  MESSAGES_REQUEST = 'MESSAGES_REQUEST',
  MESSAGES_REQUEST_SUCCESS = 'MESSAGES_REQUEST_SUCCESS',
  MESSAGES_REQUEST_FAILTURE = 'MESSAGES_REQUEST_FAILTURE',
}
export {chatsTypes, chatByIdTypes, messagesTypes};
